import { Inter } from "next/font/google";
import "./globals.css";
import {NavBar} from "./components/Navbar/NavBar";
import { AppKit } from "./context/AppKit";
import { Footer } from "./components/Footer/Footer";
import { ToastContainer, toast } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VoterDao",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ background: "linear-gradient(135deg, #09120C , #080f0B )" }}>
      <AppKit>
        <NavBar/>  
        {children}
        <Footer/>  
        <ToastContainer />
      </AppKit>
      </body>
    </html>
  );
}
